version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
        POSTGRES_USER: ${USER}
        POSTGRES_PASSWORD: ${PASSWORD}
        POSTGRES_DB: ${NAME}
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/code
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: