# Generated by Django 5.0.2 on 2024-02-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='course_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='course_id'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='url',
            field=models.CharField(blank=True, null=True, verbose_name='url'),
        ),
    ]
